### ISSUE TITLE
NAV BAR

### ISSUE THREAD

**Issue by matthewboyle9** [qazwsxedcrfvtgbyhnujmikol1234/CSWHATSGOOD#18]
The title on the nav bar acts as a button but doesn't actually do anything when pressed. Can someone either remove this functionality or make it do something useful e.i. link back to the home page

**Comment by qazwsxedcrfvtgbyhnujmikol1234** [comment]
Okay I can look into that tomorrow

**Comment by qazwsxedcrfvtgbyhnujmikol1234** [comment]
Fixed this, made it link straight back to the index page
